### ISSUE TITLE
인라인 링크란?

### ISSUE THREAD

**Issue by badgerlucy** [voidsatisfaction/CodingPangPang-Ruby#4]
인라인 링크가 뭔지 몰라서 찾아봤는데 정확히 이해를 못하겠어요ㅠ

**Comment by voidsatisfaction** [comment]
애기야 오른쪽에 보면 Labels있는데 라벨 달아줘용

그리고 질문 이렇게 하지말고 `인라인 링크란?` 이런식으로 알기쉽게 올려줘요

**Comment by voidsatisfaction** [comment]
제목만 봤을때 무슨 질문인지 모르니까

**Comment by voidsatisfaction** [comment]
참고로 오빠랑 철이는 이런식으로 해요

![screen shot 2017-01-06 at 21 18 49](https://cloud.githubusercontent.com/assets/16035247/21717672/d35a7edc-d455-11e6-878a-783c017dfa26.png)

**Comment by voidsatisfaction** [comment]
http://html5tutorial.github.io/docs/Block_and_inline_element.html

**Comment by voidsatisfaction** [comment]
인라인요소 블럭요소는 html이랑 관계가 있어요 저 링크 읽어봐용 ㅎㅎ

**Comment by voidsatisfaction** [comment]
다 읽었으면 코멘트로 👍  달아줘요

**Comment by voidsatisfaction** [comment]
👍

**Comment by voidsatisfaction** [comment]
이렇게

**Comment by badgerlucy** [comment]
👍

**Comment by voidsatisfaction** [comment]
그럼 이제 이 이슈를 닫을거에요.

닫으면 이슈 목록에서 사라지죠
